apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfsonar
  namespace: collectors
  labels:
    k8s-app: perfsonar
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: perfsonar
  template:
    metadata:
      labels:
        k8s-app: perfsonar
    spec:
      containers:
        - name: perfsonar
          image: sandci/perfsonar-collector:latest
          imagePullPolicy: Always
          command: ["/collector.py"]
          # args:
          #   - "86400"
          volumeMounts:
            - name: config-volume
              mountPath: "/config"
              readOnly: true
          resources:
            requests:
              cpu: "100m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "4Gi"

      volumes:
        - name: config-volume
          secret:
            secretName: config
